### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by Chris230291** [pimzand/tvh-muxdedup#2]
I discovered this script a couple of weeks ago and it seemed to work great.
I tried to use it again today and it is giving me errors.
I use a Docker image of TVH that has likely been updated in that time.

```
TVH_USER=admin TVH_PASS=admin /config/tvh-muxdedup.py 
Traceback (most recent call last):
  File "/config/tvh-muxdedup.py", line 326, in <module>
    main(sys.argv)
  File "/config/tvh-muxdedup.py", line 323, in main
    do_dedup()
  File "/config/tvh-muxdedup.py", line 151, in do_dedup
    channelnames.append({'uuid': service['uuid'], 'svcname': service['svcname']})
KeyError: 'svcname'
```

Thanks for making this... Should be built in to TVH.

**Comment by pimzand** [comment]
It appears you have a channel mapped that has no name.
Do you see something odd in any of your channels?
If so, delete the channel and try again.

**Comment by Chris230291** [comment]
Thanks for the reply.
Today I unmapped all bouquets and your script started working again.

In the future I will look for channels with no/bad names.

Thanks,
Chris
